### PR TITLE
Add zeronsd quickstart

### PR DESCRIPTION
**Pull request by erikh**
this also changes from using npm to yarn, and a few other minor details in the build pipeline surrounding docker.

this should help adoption from external people so they don't need our toolsets to generate docs.

### CODE REVIEW

**Comment by laduke** [comment]
Could be my internets at the moment, but the docker demo thing is taking like 30 minutes to build (docker for mac).
Just curious how long should be expected?

oops it just ended with `Error: EACCES: permission denied, open '/.yarnrc'`

**Comment by erikh** [comment]
no idea; it's working fine here. I'll see if I can repro

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by erikh** [comment]
try now; run `git clean -fdx` before the first swing

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by erikh** [comment]
Please note it's going to want to fetch all packaages; it does this the first time but additional times should not incur the penalty.

**Comment by laduke** [comment]
On Docker for Mac, I'm getting `Error: EACCES: permission denied, open '/.yarnrc'` 
unless I remove `-u $$(id -u):$$(id -g)` from the docker run command. 
Not sure if this is a proper. 

--- 

 ironically, npm goes much faster than yarn for me in this Dockerfile.

**Comment by erikh** [comment]
probably because of the parallelism, I'm guessing.

ok, if this isn't working, i won't waste your time on it further. I can back it out or you can just use your host stuff. let me know what you'd prefer.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by laduke** [comment]
I appreciate trying to make it easier. Bummer my mac/docker isn't cooperating. 

I think We can leave it in? I don't think it affects anything. And we can figure it out later.

**Comment by erikh** [comment]
up to you. Here's an encouraging image from my childhood to guide your way.

**Pull request merged**
