### PR TITLE
WIP: more API docs + nav/sidebar cleanup

### PR DESCRIPTION
**Pull request by rcoder**
Adding API docs + trying to clean up the left-hand navigation a bit.

Not quite ready for final review + merge, but I wanted to get 👀 on this in its current state since much of the top-level nav has been shuffled.

### CODE REVIEW

**Comment by laduke** [comment]
Thanks for doing this. I loaded it up and looked through it. Seems good to me. 

There's one markdown lint complaint in CI

docs/api/tokens.md:9 MD025/single-title/single-h1 Multiple top-level headings in the same document [Context: "# Using ZeroTier API Tokens"]

**Review by laduke — CHANGES_REQUESTED** [review]
`npm run lint:markdown `

```
docs/api/tokens.md:9 MD025/single-title/single-h1 Multiple top-level headings in the same document [Context: "# Using ZeroTier API Tokens"]
```

**Comment by rcoder** [comment]
I fixed the linter warning and believe what's here is probably a sufficient improvement to be worth shipping. Feedback welcome; just trying to clear this out of the queue before embarking on the next set of changes.

**Review by laduke — APPROVED** [review]
awesome!

**Pull request merged**
