### PR TITLE
Update and simplify docs

### PR DESCRIPTION
**Pull request by joseph-henry**

### CODE REVIEW

**Comment by glimberg** [comment]
It's failing in Drone right now

**Comment by glimberg** [comment]
https://drone.ci.lab/zerotier/docs/162/1/2

**Comment by glimberg** [comment]
unfortunately, autogenerating the sidebar is going to kill links to the external libzt docs

**Comment by joseph-henry** [comment]
To summarize latest work:

 - This PR doesn't break any URLs or introduce any significant content changes
 - the openAPI plugin doesn't seem to play well with autogenerated sidebars so we still define that manually (but only that)
 - Some items that were commented out of the sidebars.js file were moved to `./draft`
 - Some items like ZeroNSD and API Docs have slightly different category ordering/structure but the URLs remain the same (I'm proposing more drastic changes in the next PR anyway so I wouldn't sweat this)
 
Ideally from the content consumer's perspective not much has changed. If we're all still ok with what's here I can merge this and get the next content PR ready.

**Comment by joseph-henry** [comment]
@zt-joy I'm going to look into implementing the category indices you mentioned
@zt-grant @zt-laduke See anything wonky here? It works on my machine and mostly looks the same as current.
@rcoder The next PR is going to be a content re-org that we can bring everyone into to discuss

**Comment by laduke** [comment]
going to get this up and running locally asap

**Comment by joseph-henry** [comment]
There was a theme adjustment to get around some deprecation errors when upgrading so you might notice some font sizes a little different but I think they're very minor.

**Comment by laduke** [comment]
i see a couple funky articles out of their categories

Screenshot 2023-09-11 at 3 39 05 PM

I just did ` yarn install; yarn start `

**Comment by laduke** [comment]
haha nevermind
those are uncommitted markdown files in my repo that i forgot about

**Comment by laduke** [comment]
some of the categories are in a different order but we can futz with that later probably IMO

**Comment by glimberg** [comment]
looking good to me so far

**Comment by joseph-henry** [comment]
> some of the categories are in a different order but we can futz with that later probably IMO

Yes they are but I'm going to re-org them in the next content PR anyway. I just wanted to have a good stable commit before I started messing with the structure of content

**Pull request merged**
